### ISSUE TITLE
redis-port 命令行解析错误

### ISSUE THREAD

**Issue by huyutian** [CodisLabs/redis-port#20]
redis-port 解析命令行，按照正确的usage输入命令，但是正常功能无法执行，总是输出 
Usage:
	redis-port decode   [--ncpu=N]  [--parallel=M]  [--input=INPUT]  [--output=OUTPUT]
	redis-port restore  [--ncpu=N]  [--parallel=M]  [--input=INPUT]   --target=TARGET   [--auth=AUTH]  [--extra] [--faketime=FAKETIME]  [--filterdb=DB]  ... 
查阅最新的代码，
源码文件中 redis-port/blob/master/cmd/main.go  85行 d, err := docopt.Parse(usage, nil, true, "", false)
docopt.Parse第二个参数为nil 是不是有问题，觉得应该是 os.Args ???

**Comment by spinlock** [comment]
你输入的命令是什么？

**Comment by spinlock** [comment]
我去查了一下 docopt.go 的代码[链接](https://github.com/docopt/docopt.go/blob/master/docopt.go#L70)，当 第二个参数 缺省使用 os.Args，所以这么写是对的。

我怀疑还是有些地方写的不太正确。
