### ISSUE TITLE
运行redis-port，一直报错panic: runtime error

### ISSUE THREAD

**Issue by LeechanX** [CodisLabs/redis-port#24]
redis版本2.8.19
go版本1.6.3

 ./redis-port sync -f 127.0.0.1:6379 -t 127.0.0.1:6381 -n 1
panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xb code=0x1 addr=0x0 pc=0x8181ffb]

goroutine 1 [running]:
panic(0x8214460, 0x18528030)
	/usr/local/go/src/runtime/panic.go:481 +0x326
sync/atomic.LoadUint64(0x1855c104, 0x805c9d2, 0x8249610)
	/usr/local/go/src/sync/atomic/asm_386.s:159 +0xb
github.com/CodisLabs/redis-port/pkg/libs/log.(*LogLevel).Test(0x1855c104, 0x4, 0x0, 0x18d414d0)
	/home/leechanx/go/src/github.com/CodisLabs/redis-port/pkg/libs/log/log.go:72 +0x21
github.com/CodisLabs/redis-port/pkg/libs/log.(*Logger).isDisabled(0x1855c0f0, 0x4, 0x0, 0x0)
	/home/leechanx/go/src/github.com/CodisLabs/redis-port/pkg/libs/log/log.go:167 +0x45
github.com/CodisLabs/redis-port/pkg/libs/log.Infof(0x8258ff0, 0x13, 0x0, 0x0, 0x0)
	/home/leechanx/go/src/github.com/CodisLabs/redis-port/pkg/libs/log/log.go:529 +0x3e
main.main()
	/home/leechanx/redis-port/cmd/main.go:176 +0x1136

**Comment by spinlock** [comment]
你是在 64位系统上跑了 32位程序？

2016年7月20日星期三，leechanx <notifications@github.com> 写道：
