### ISSUE TITLE
关于数据的sync

### ISSUE THREAD

**Issue by caozhenhuamail** [CodisLabs/redis-port#25]
[root@iZ23y2cpqz2Z redis-port]# ./bin/redis-port sync --from 10.168.22.140:6379 --filterdb=3 --target 10.251.241.246:19000
2016/07/28 12:39:17 [INFO] set ncpu = 2, parallel = 2
2016/07/28 12:39:17 [INFO] sync from '10.168.22.140:6379' to '10.251.241.246:19000'
2016/07/28 12:39:18 [INFO] +
2016/07/28 12:39:19 [INFO] -
2016/07/28 12:39:19 [INFO] rdb file = 37806381
2016/07/28 12:39:20 [INFO] total=37806381 -      9613493 [ 25%]  entry=0             ignore=1472        
2016/07/28 12:39:21 [INFO] total=37806381 -     20463960 [ 54%]  entry=0             ignore=3010        
2016/07/28 12:39:22 [INFO] total=37806381 -     34201728 [ 90%]  entry=0             ignore=5363        
2016/07/28 12:39:23 [INFO] total=37806381 -     37806381 [100%]  entry=0             ignore=7258        
2016/07/28 12:39:23 [INFO] sync rdb done
2016/07/28 12:39:24 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:39:25 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:26 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:27 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:28 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:39:29 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:30 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:31 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:32 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:33 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:34 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:35 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:36 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:37 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:38 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:39:39 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:40 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:41 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:42 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:43 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:44 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:45 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:46 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:47 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:48 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:39:49 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:50 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:51 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:52 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:53 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:54 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:55 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:56 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:57 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:58 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:39:59 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:40:00 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:01 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:02 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:03 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:04 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:05 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:06 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:07 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:08 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:09 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:40:10 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:11 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:12 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:13 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:14 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:15 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:16 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:17 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:18 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:19 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:40:20 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:21 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:22 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:23 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:24 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:25 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:26 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:27 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:28 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:29 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:40:30 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:31 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:32 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:33 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:34 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:35 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:36 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:37 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:38 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:39 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:40:40 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:41 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:42 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:43 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:44 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:45 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:46 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:47 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:48 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:49 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:40:50 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:51 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:52 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:53 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:54 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:55 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:56 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:57 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:58 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:40:59 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:41:00 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:01 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:02 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:03 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:04 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:05 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:06 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:07 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:08 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:09 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:41:10 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:11 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:12 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:13 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:14 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:15 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:16 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:17 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:18 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:19 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:41:20 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:21 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:22 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:23 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:24 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:25 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:26 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:27 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:28 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:29 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:41:30 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:31 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:32 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:33 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:34 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:35 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:36 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:37 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:38 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:39 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:41:40 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:41 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:42 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:43 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:44 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:45 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:46 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:47 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:48 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:49 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:41:50 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:51 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:52 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:53 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:54 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:55 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:56 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:57 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:58 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:41:59 [INFO] sync:  +forward=1      +nbypass=0      +nbytes=14
2016/07/28 12:42:00 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:42:01 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:42:02 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:42:03 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:42:04 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:42:05 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
2016/07/28 12:42:06 [INFO] sync:  +forward=0      +nbypass=0      +nbytes=0
......

以上的过程只要有sync rdb done 就算成功了吗,还是的一直等待那, 因为一直在forward; 刷屏;

我只能ctrl + c了.

**Comment by spinlock** [comment]
这个问题 问过很多了 你搜一下 issue？

不会停的

2016年7月28日星期四，caozhenhuamail <notifications@github.com> 写道：

**Comment by spinlock** [comment]
可以到 codis 下搜一下 issue

2016年7月28日星期四，caozhenhuamail <notifications@github.com> 写道：

**Comment by caozhenhuamail** [comment]
O ,好的,我找下以前的问题,谢谢.
