### ISSUE TITLE
Error when sync or dump 

### ISSUE THREAD

**Issue by GitProBo** [CodisLabs/redis-port#26]
2016/08/02 14:04:33 [INFO] set ncpu = 4, parallel = 4
2016/08/02 14:04:33 [INFO] sync from '10.1.101.168:6379' to '10.1.100.219:7018'
2016/08/02 14:04:34 [INFO] -
2016/08/02 14:04:35 [INFO] -
2016/08/02 14:04:36 [INFO] -
2016/08/02 14:04:37 [INFO] -
2016/08/02 14:04:38 [INFO] -
2016/08/02 14:04:39 [INFO] -
2016/08/02 14:04:39 [PANIC] invalid sync response = '$EOF:d7a06afab211ab2508092e1c019e4cdbac1908bb
', n = 0
[error]: strconv.ParseInt: parsing "EOF:d7a06afab211ab2508092e1c019e4cdbac1908bb": invalid syntax
[stack]: 
    0   /usr/lib/golang/src/github.com/CodisLabs/redis-port/cmd/utils.go:122
            main.waitRdbDump.func1

**Comment by spinlock** [comment]
是不是这个？

https://github.com/CodisLabs/redis-port/issues/23
