### ISSUE TITLE
使用redis-port sync 之后一直不停的刷新下面内容

### ISSUE THREAD

**Issue by 16boke** [CodisLabs/redis-port#27]
您好：
我使用redis-port sync...命令来将redis的数据同步到codis中，但是一直出现下面内容在刷新，
请问：
1、sync是不是永远会执行下去？
2、“sync:  +forward=12547  +nbypass=0      +nbytes=1588130”具体每个值是什么意思呢？比如+forward、+nbypass？
下面是刷屏内容：
2016/09/21 18:34:59 [INFO] sync:  +forward=12547  +nbypass=0      +nbytes=1588130
2016/09/21 18:35:00 [INFO] sync:  +forward=12121  +nbypass=0      +nbytes=1524604
2016/09/21 18:35:01 [INFO] sync:  +forward=12721  +nbypass=0      +nbytes=1609632
2016/09/21 18:35:02 [INFO] sync:  +forward=11180  +nbypass=0      +nbytes=1405242
2016/09/21 18:35:03 [INFO] sync:  +forward=11215  +nbypass=0      +nbytes=1414128
2016/09/21 18:35:04 [INFO] sync:  +forward=11677  +nbypass=0      +nbytes=1474217
2016/09/21 18:35:05 [INFO] sync:  +forward=12818  +nbypass=0      +nbytes=1617235
2016/09/21 18:35:06 [INFO] sync:  +forward=12489  +nbypass=0      +nbytes=1578302
2016/09/21 18:35:07 [INFO] sync:  +forward=12898  +nbypass=0      +nbytes=1624360
2016/09/21 18:35:08 [INFO] sync:  +forward=12558  +nbypass=0      +nbytes=1584386
2016/09/21 18:35:09 [INFO] sync:  +forward=10635  +nbypass=0      +nbytes=1342169
2016/09/21 18:35:10 [INFO] sync:  +forward=10354  +nbypass=0      +nbytes=1309103
2016/09/21 18:35:11 [INFO] sync:  +forward=12291  +nbypass=0      +nbytes=1548088
2016/09/21 18:35:12 [INFO] sync:  +forward=4331   +nbypass=0      +nbytes=549110
2016/09/21 18:35:13 [INFO] sync:  +forward=11431  +nbypass=0      +nbytes=1441636
2016/09/21 18:35:14 [INFO] sync:  +forward=10927  +nbypass=0      +nbytes=1376418
......

**Comment by spinlock** [comment]
https://github.com/CodisLabs/codis/issues/318

看最后～
