### ISSUE TITLE
rdb version 7

### ISSUE THREAD

**Issue by scu2013** [CodisLabs/redis-port#32]
redis 3.2开始使用quickList类型来存储了，而且不再兼容前面的版本，会支持rdb version 7吗？

**Comment by spinlock** [comment]
@scu2013 这很尴尬。因为我并不知道。

所以最简单的尝试是找一个 rdb 文件用 redis-port decode 它一下试试看。

之前我对 rdb v7 做过兼容，但是不知道覆盖的是不是完全。
我没有足够多的机会进行测试。但是至少 redis 提供的测试我是能跑过的。

你可以跑一下，然后告诉我们结果。

谢谢~
