### ISSUE TITLE
同步后，内存和key数量不一致

### ISSUE THREAD

**Issue by liquanzhou** [CodisLabs/redis-port#35]
master的内存使用是9G，440W的key，用这个工具同步到其他redis上，显示使用内存只有6G，400W的key。
少了几个内存使用和40W的key。
也简单的验证了一些key，都是存在的。 但是还是不明白差的地方在哪，是否能保证数据一致？

**Comment by spinlock** [comment]
检查 expire 时间。redis 过期是 lazy 的。

不放心的话，用一个干净的 redis 作为 slave 挂到 master 上，然后比较这个 slave 和刚刚从 redis-port 恢复的 redis 的数据即可。

**Comment by liquanzhou** [comment]
非常感谢！
用keys 减去expires的数量是一致的。
