### ISSUE TITLE
数据迁移目标codis集群的database选择

### ISSUE THREAD

**Issue by ghdjl** [CodisLabs/redis-port#37]
你好，请问redis-port支持target 的database选择吗？
例如，我要把某个redis集群中的数据迁移到codis3.2中的database 3

**Comment by lvdelu** [comment]
这个目前不支持，只支持db0库

**Comment by spinlock** [comment]
你的这个需求都太复杂了。如果真的有必要的话，改 sync.go 的代码。里面的逻辑很简单。

https://github.com/CodisLabs/redis-port/blob/master/cmd/sync.go
