### ISSUE TITLE
decode 出现这个，是什么原因

### ISSUE THREAD

**Issue by wnaghuixin** [CodisLabs/redis-port#38]
[root@92780d52277f 6379]# ../../cmd decode --n=2 --i=./dump.rdb --o=test
2017/08/21 09:12:56 main.go:189: [INFO] set ncpu = 2, parallel = 2
2017/08/21 09:12:56 decode.go:45: [INFO] decode from './dump.rdb' to 'test'
2017/08/21 09:12:56 utils.go:361: [PANIC] parse rdb header error
[error]: verify version, invalid RDB version number 8
    1   /home/gopath/src/github.com/CodisLabs/redis-port/pkg/rdb/loader.go:44
            github.com/CodisLabs/redis-port/pkg/rdb.(*Loader).Header
    0   /home/gopath/src/github.com/CodisLabs/redis-port/cmd/utils.go:360
            main.newRDBLoader.func1
        ... ...
[stack]: 
    0   /home/gopath/src/github.com/CodisLabs/redis-port/cmd/utils.go:361
            main.newRDBLoader.func1

**Comment by spinlock** [comment]
Redis 项目经常修改 RDB 的格式。前后不兼容。你这种应该是 Redis4.x 的 RDB。目前不支持。。

**Comment by wnaghuixin** [comment]
对，是4.x的版本。
