### ISSUE TITLE
ERR wrong number of arguments for 'restore' command

### ISSUE THREAD

**Issue by zhangwei0181** [CodisLabs/redis-port#41]
./redis-port restore --input=/root/dump1.rdb --target=10.159.3.16:6379 --auth=abcabc --redis
2017/09/14 15:13:09 main.go:189: [INFO] set ncpu = 2, parallel = 2
2017/09/14 15:13:09 restore.go:53: [INFO] restore from '/root/dump1.rdb' to '10.159.3.16:6379'
2017/09/14 15:13:09 utils.go:216: [PANIC] RESTORE command error
[error]: ERR wrong number of arguments for 'restore' command

i followed the help information ,but failed . why?
redis-port restore  [--ncpu=N]  [--parallel=M]  [--input=INPUT]  [--faketime=FAKETIME] [--extra] [--filterdb=DB] --target=TARGET [--auth=AUTH] [--redis|--codis]

**Comment by spinlock** [comment]
Here's the source code, https://github.com/CodisLabs/redis-port/blob/master/cmd/utils.go#L214
Please tell me the version of your redis instance.

**Comment by zhangwei0181** [comment]
I already read the source code but I am not familiar with the go , so  I did not find the reason.
I used v1.2.1

**Comment by spinlock** [comment]
Oh, what about your redis version?

**Comment by zhangwei0181** [comment]
redis 2.8

**Comment by spinlock** [comment]
Any update ?

**Comment by zhangwei0181** [comment]
no reproduce now
