### ISSUE TITLE
/bin/sh: line 1: ./autogen.sh: No such file or directory

### ISSUE THREAD

**Issue by imshi** [CodisLabs/redis-port#47]
redis-4.x-cgo分支make的时候提示找不到这个文件...

**Comment by git-shine** [comment]
clone到的项目redis-port/third_party目录为空，请问一下如何处理

**Comment by imshi** [comment]
make --debug
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu
Reading makefiles...
Updating goal targets....
 File `build-all' does not exist.
   File `redis-sync' does not exist.
     File `build-deps' does not exist.
       File `build-jemalloc' does not exist.
      Must remake target `build-jemalloc'.
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for x86_64-redhat-linux-gnu
Reading makefiles...
Updating goal targets....
 File `jemalloc' does not exist.
Must remake target `jemalloc'.
/bin/sh: line 1: ./autogen.sh: No such file or directory
make[1]: *** [jemalloc] Error 127
make: *** [build-jemalloc] Error 2

**Comment by spinlock** [comment]
git submodule 有关的操作

谷冬 <notifications@github.com>于2018年3月30日 周五13:10写道：

**Comment by hongliuliao** [comment]
同遇到这个问题, 能把编译的命令写在readme么?
