### ISSUE TITLE
迁移数据时需要把原集群里key的一部分和节点相关的信息移除掉

### ISSUE THREAD

**Issue by Martian101** [CodisLabs/redis-port#48]
你好！我们原先的Redis集群方案，存储在Redis的key里额外包含了和具体redis节点相关的信息。现在想切换到Codis，想把这部分信息移除掉。请问有办法在迁移的时候修改key去实现这样的效果么？

**Comment by spinlock** [comment]
不支持。
但是你看一下 redis-port 代码，，并不复杂，根据需求自己改改我觉得难度不大。本质是在一个 key 一个 key 的迁移。但是之后的在追
backlog 的时候就会很复杂了，要具体问题具体分析。

2018-04-12 14:54 GMT+08:00 zqzhao5 <notifications@github.com>:

**Comment by Martian101** [comment]
谢谢你的回复！请问这块具体的文档有么？代码一点点看有点繁琐了，有文档的话可以参考着看，感谢！

**Comment by Martian101** [comment]
已经解决掉了，谢谢！
