### ISSUE TITLE
无法恢复数据

### ISSUE THREAD

**Issue by qianghong000** [CodisLabs/redis-port#50]
/data/package/redis-port/redis-port restore -i save.rdb -t 192.168.30.200:6380
2018/04/18 17:53:20 main.go:189: [INFO] set ncpu = 4, parallel = 4
2018/04/18 17:53:20 restore.go:53: [INFO] restore from 'save.rdb' to '192.168.30.200:6380'
2018/04/18 17:53:20 utils.go:211: [PANIC] SLOTSRESTORE command error
[error]: ERR unknown command 'SLOTSRESTORE'
[stack]: 
    1   /home/travis/gopath/src/github.com/CodisLabs/redis-port/cmd/utils.go:211
            main.restoreRdbEntry
    0   /home/travis/gopath/src/github.com/CodisLabs/redis-port/cmd/restore.go:102
            main.(*cmdRestore).RestoreRDBFile.func1.1
        ... ...

**Comment by spinlock** [comment]
这个版本的依赖 redis 打过 patch

你可以试试 *-cgo branch 的代码

shihong.qiang <notifications@github.com>于2018年4月18日 周三17:56写道：
