### ISSUE TITLE
WRONGTYPE Operation against a key holding the wrong kind of value

### ISSUE THREAD

**Issue by vs333** [CodisLabs/redis-port#51]
2018/04/27 10:59:50 sync.go:103: [INFO] +
2018/04/27 10:59:51 sync.go:109: [INFO] sync: runid = "969c3a1e19ca54b66b2ad780d60edd43472a3a09", offset = 519121821
2018/04/27 10:59:51 sync.go:111: [INFO] sync: rdb file = 1663327129 (1.55gb)
2018/04/27 10:59:51 sync.go:208: [INFO] sync: (r/f,s/f,s) = (read,rdb.forward,rdb.skip/rdb.forward,rdb.skip)
2018/04/27 10:59:52 sync.go:250: [INFO] sync: rdb = 1663327129 - [ 24.74%]   (r/f,s/f,s)=(786432/7628,0/0,0)   ~  (768.00kb/-,-/-,-)    ~  speed=(768.00kb/7628,0/0,0)
2018/04/27 10:59:53 sync.go:250: [INFO] sync: rdb = 1663327129 - [ 48.86%]   (r/f,s/f,s)=(1441792/14493,0/0,0)     ~  (1.38mb/-,-/-,-)  ~  speed=(640.00kb/6865,0/0,0)
2018/04/27 10:59:54 sync.go:250: [INFO] sync: rdb = 1663327129 - [ 67.32%]   (r/f,s/f,s)=(2752512/18423,0/0,0)     ~  (2.62mb/-,-/-,-)  ~  speed=(1.25mb/3930,0/0,0)
2018/04/27 10:59:54 libs.go:462: [PANIC] fetch redigo reply failed
[error]: WRONGTYPE Operation against a key holding the wrong kind of value
[stack]:
    2   /home/travis/gopath/src/github.com/CodisLabs/redis-port/cmd/libs.go:462
            main.redigoGetResponse
    1   /home/travis/gopath/src/github.com/CodisLabs/redis-port/cmd/libs.go:588
            main.doRestoreDBEntry.func3
    0   /home/travis/gopath/src/github.com/CodisLabs/redis-port/cmd/libs.go:314
            main.(*Job).Run.func1
        ... ...

做同步的时候报错WRONGTYPE Operation against a key holding the wrong kind of value

**Comment by spinlock-pony** [comment]
https://github.com/CodisLabs/redis-port/pull/46 ?  我猜测是我之前一个 typo 把数据类型写错了。

**Comment by spinlock** [comment]
试试这个？https://github.com/CodisLabs/redis-port/releases/tag/v2.0-beta
