### ISSUE TITLE
make

### ISSUE THREAD

**Issue by PogiLong** [CodisLabs/redis-port#53]
/bin/sh: 2: ./autogen.sh: not found
Makefile:59: recipe for target 'jemalloc' failed
make[1]: *** [jemalloc] Error 127
Makefile:63: recipe for target 'build-jemalloc' failed
make: *** [build-jemalloc] Error 2

**Comment by spinlock** [comment]
1. 安装 autogen 工具
2. git submodule init & git submodule update
