### ISSUE TITLE
编译命令

### ISSUE THREAD

**Issue by yxb0926** [CodisLabs/redis-port#55]
能给下编译命令吗？

**Comment by wllenyj** [comment]
简单的：make
复杂说：
先把third_party目录的submodules更新下来，然后再make
如果报错说"Newer version of jemalloc required"
编辑Makefile文件的jemalloc:
把./autogen.sh --with-jemalloc-prefix="je_"  && make -j
改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
--with-version=随便写一个大于2的
NND害我浪费了2小时看源码，结果弄完了，发现云上的redis不让普通用户执行dump，白弄。。。

**Comment by jlcoding** [comment]
我真的服了

**Comment by iamxvbaba** [comment]
> 简单的：make
> 复杂说：
> 先把third_party目录的submodules更新下来，然后再make
> 如果报错说"Newer version of jemalloc required"
> 编辑Makefile文件的jemalloc:
> 把./autogen.sh --with-jemalloc-prefix="je_" && make -j
> 改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
> --with-version=随便写一个大于2的
> NND害我浪费了2小时看源码，结果弄完了，发现云上的redis不让普通用户执行dump，白弄。。。

把third_party目录的submodules更新下来 是各自make 还是直接把目录都放在redis-port make?

**Comment by iamxvbaba** [comment]
> 4.5.0-0-g00000

老哥 
把./autogen.sh --with-jemalloc-prefix="je_" && make -j
改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
不生效啊 还是报"Newer version of jemalloc required"

**Comment by iamxvbaba** [comment]
> 简单的：make
> 复杂说：
> 先把third_party目录的submodules更新下来，然后再make
> 如果报错说"Newer version of jemalloc required"
> 编辑Makefile文件的jemalloc:
> 把./autogen.sh --with-jemalloc-prefix="je_" && make -j
> 改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
> --with-version=随便写一个大于2的
> NND害我浪费了2小时看源码，结果弄完了，发现云上的redis不让普通用户执行dump，白弄。。。

老哥
把./autogen.sh --with-jemalloc-prefix="je_" && make -j
改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
不生效啊 还是报"Newer version of jemalloc required"

**Comment by wllenyj** [comment]
> > 简单的：make
> > 复杂说：
> > 先把third_party目录的submodules更新下来，然后再make
> > 如果报错说"Newer version of jemalloc required"
> > 编辑Makefile文件的jemalloc:
> > 把./autogen.sh --with-jemalloc-prefix="je_" && make -j
> > 改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
> > --with-version=随便写一个大于2的
> > NND害我浪费了2小时看源码，结果弄完了，发现云上的redis不让普通用户执行dump，白弄。。。
> 
> 老哥
> 把./autogen.sh --with-jemalloc-prefix="je_" && make -j
> 改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
> 不生效啊 还是报"Newer version of jemalloc required"

那估计是源码又修改判断逻辑了。。。。

**Comment by iamxvbaba** [comment]
> > > 简单的：make
> > > 复杂说：
> > > 先把third_party目录的submodules更新下来，然后再make
> > > 如果报错说"Newer version of jemalloc required"
> > > 编辑Makefile文件的jemalloc:
> > > 把./autogen.sh --with-jemalloc-prefix="je_" && make -j
> > > 改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
> > > --with-version=随便写一个大于2的
> > > NND害我浪费了2小时看源码，结果弄完了，发现云上的redis不让普通用户执行dump，白弄。。。
> > 
> > 
> > 老哥
> > 把./autogen.sh --with-jemalloc-prefix="je_" && make -j
> > 改成./autogen.sh --with-jemalloc-prefix="je_" --with-version=4.5.0-0-g00000 && make -j
> > 不生效啊 还是报"Newer version of jemalloc required"
> 
> 那估计是源码又修改判断逻辑了。。。。

我现在执行make的时候报
src/ctl.c:1127:1: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘{’ token
 {
真的难受啊,不知道是不是因为jemalloc导入了c++文件还是因为我gcc(4.8.5)版本的问题。
